// The sequence of triangle numbers is generated by adding the natural numbers.
// So the 7th triangle number would be 1+2+3+4+5+6+7=28. 28 is the first
// triangle number to have over five divisors. What is the value of the first
// triangle number to have over five hundred divisors?

// A max number arrived at by trial and error to cut down the problem space
// We will go until we hit the 20,000th triangle number
#define MAX_TRIANGLE_NUM 20000
#define NUM_DIVISORS 500

#include <stdio.h>

int main() {
  int triangleNums[MAX_TRIANGLE_NUM] = {0};

  for (int i = 1; i < MAX_TRIANGLE_NUM; i++) {
    for (int j = i; j < MAX_TRIANGLE_NUM; j += i) {
      triangleNums[j]++;
    }

    int numFactors = (i % 2 == 0 ? triangleNums[i - 1] * triangleNums[i / 2]
                                 : triangleNums[(i - 1) / 2] * triangleNums[i]);
    if (numFactors > NUM_DIVISORS) {
      printf("%d\n", (i - 1) * i / 2);
      break;
    }
  }
  return 0;
}
